name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Unzip project
      run: unzip KitchenStock.zip

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Give permission
      run: chmod +x KitchenStock/gradlew

    - name: Build APK
      run: cd KitchenStock/KitchenStock && ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: KitchenStock/app/build/outputs/apk/debug/app-debug.apk
